Algoritmo "questao5"

Var

   x : real

Inicio

   escreva("Digite um numero de 1 a 12: ")
   leia(x)
   
   escolha (x)
   caso 1
      escreva("domingo")
   caso 2
      escreva("segunda")
   caso 3
      escreva("terca")
   caso 4
      escreva("quarta")
   caso 5
      escreva("quinta")
   caso 6
      escreva("sexta")
   caso 7
      escreva("sabado")
   outrocaso
      escreva("Somente numeros de 1 a 7!!")
   fimescolha
      
Fimalgoritmo